version = 0.1
[default.deploy.parameters]
stack_name = "ekksamen2023"
resolve_s3 = true
s3_prefix = "ekksamen2023"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
